general{
	immediate_render=true
	ignore_empty_input=true
	hide_cursor=true
}
background{
	color=rgba(255,0,0,0.2)
	path=~/wallpaper/LockScreen.png
}
auth{
	fingerprint:enabled=true
}

animations {  
    enabled = true  
    bezier = linear, 1, 1, 0, 0  
    animation = fadeIn, 1, 5, linear  
    animation = fadeOut, 1, 5, linear  
    animation = inputFieldDots, 1, 2, linear  
}

# for Hour
label {
	monitor =
	text = cmd[update:1000] date +'LOCK_CUR_TIME=%H:'
	color = rgba(e01c6899)
	font_size = 10
	font_family = FiraCode Nerd Font Bold
	position = -28%, -30%
	halign = center
	valign = center
}

# for Minutes
label {
	monitor =
	text = cmd[update:1000] date +'%M'
	color = rgba(e01c6899)
	font_size = 10
	font_family = FiraCode Nerd Font Bold
	position = -24%, -30%
	halign = center
	valign = center
}

# Day-Month-Date
label {
	monitor =
	text = cmd[update:1000] date +'LOCK_CUR_DATE=%d %B, %a.'
	color = rgba(e01c6899)
	font_size = 10
	font_family = FiraCode Nerd Font Propo
	position = -18%, -30%
	halign = center
	valign = center
}

# Failed attempts
label {
  monitor =
  text = LOCK_SEC_FA=$ATTEMPTS
  color = rgba(e01c6899)
  font_size = 10
  font_family = FiraCode Nerd Font Propo
  position = 32%, -30%
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
	monitor =
	size = 60, 60
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(255, 255, 255, 0.1)
	font_color = rgb(200, 200, 200)
  placeholder_text =
  fail_text =
	fade_on_empty = false
	font_family = SF Pro Display Bold
	hide_input = true
	position = 7,10%
	halign = center
	valign = center
}
